language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - SYMFONY_VERSION=2.0.*
  - SYMFONY_VERSION=2.1.*
  - SYMFONY_VERSION=2.2.*
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=dev-master

before_script:
  - composer self-update
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}
  - composer install --dev

script: phpunit --coverage-text

notifications:
  email: mb@lunetics.com
